Mongodb refactoring
Multi-Agent-io/feecc-workbench-daemon pull request #41
Opened 2024-03-06 13:48 UTC by Berlimor

2024-03-06 14:23 UTC, PaTara43 reviewed
Структура мне понятна, в принципе. Вопрос только к тому, как закрывается соеинение и будет ли их открываться много (на каждый вызов враппера из модуля, например, employee)

И не хватает чуть более развернутой документации, пояснений ко входным и выходным переменным. Чуть подробнее в докстринге. 

По расположению модулей к @timofeev41 вопрос. он посмотрит вечером

2024-03-06 14:45 UTC, Berlimor commented
Насчёт соединений, по идее будет одно соединение, которое закрывается при остановке работы app.py (закрытие выполняется через lifespan event). 

По поводу входных и выходных переменных - немного не понял. Вроде у каждой функции есть возвращаемый тип переменной, у каждого входного параметра - тип этого параметра.

2024-03-06 15:50 UTC, PaTara43 commented
Про соединения понял. 
Я не про тип переменных, а про описание)
Плюс не у всех функцйи есть докстринг, давай заведем для проформы

2024-03-08 14:01 UTC, timofeev41 requested changes
ярко но надо чуть допилить

2024-03-08 14:01 UTC, timofeev41 commented on src/app.py
> +import src.routers._workbench_router as _workbench_router
Давайте больше не будем делать модули приватными))) сделай просто employee_router и тд

2024-03-08 14:01 UTC, timofeev41 commented on src/database/database.py
> +base_mongodb_wrapper = _BaseMongoDbWrapper()
константы и синглтоны надо по хорошему обзывать BASE_MONGO_WRAPPER, но тут лучше чтобы было просто BaseMongoDbWrapper = _... иначе непонятно

2024-03-08 14:01 UTC, timofeev41 commented on src/dependencies.py
> +from .prod_schema.prod_schema_wrapper import prod_schema_wrapper
А нельзя без относительных импортов тут? сделать как ниже абсолютный путь

2024-03-08 14:01 UTC, timofeev41 commented on src/prod_schema/prod_schema_wrapper.py
> +
концепция засовывать все это в папки не очень давай лучше папку сделаем database и в ней будут лежать эти врапперы без папки

2024-03-08 14:01 UTC, timofeev41 commented on src/database/database.py
> +    def read(self, collection: str, filters: dict[str, Any] = {}, **kwargs) -> list[Document]:
read непонятно что это, сделай его find как просто в монгодб

2024-03-08 14:01 UTC, timofeev41 commented on src/database/database.py
> +
я думаю можно еще добавить метод .find_one чтоб доставать один нужный документ по фильтру или возвращать None без превращения в лист, а то такое много где надо

2024-03-08 14:01 UTC, timofeev41 commented on src/feecc_workbench/WorkBench.py
> +            parent_schema = await prod_schema_wrapper.get_schema_by_id(schema.parent_schema_id)
и все эти врапперы лучше бы тоже называть нормально а не как обычную переменную, все таки это синглтон (полноценный класс)

2024-03-08 14:01 UTC, timofeev41 commented on src/prod_stage/prod_stage_wrapper.py
> +    def _bulk_push_production_stages(self, production_stages: list[ProductionStage]) -> None:
а почему оно приватное? не надо

2024-03-11 10:11 UTC, Berlimor commented on src/prod_schema/prod_schema_wrapper.py
> +
Не уверен в этом. В основном (2 из 3) папки - это модули, где лежит соответствующая информация. В юните - всё про юнит и взаимодействие с ним и тп. Только у прод схемы один файл в папке лежит. 
Учитывая это, всё равно убрать вопперы?

2024-03-11 10:18 UTC, Berlimor commented on src/prod_stage/prod_stage_wrapper.py
> +    def _bulk_push_production_stages(self, production_stages: list[ProductionStage]) -> None:
Оно приватное, потому что было приватным изначально. По идее не должно быть, я просто оставил, как было :)

2024-03-11 20:32 UTC, timofeev41 commented on src/prod_schema/prod_schema_wrapper.py
> +
тогда ладно

2024-03-11 20:32 UTC, timofeev41 approved these changes

2024-03-12 08:08 UTC, merged